# Generated by Django 5.0.6 on 2024-07-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('isactive', models.BooleanField(default=True)),
                ('usertype', models.IntegerField(default=0)),
                ('profilephoto', models.ImageField(default='user/1.png', upload_to='user/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
