# Generated by Django 5.0.6 on 2024-08-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CsideApp', '0004_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
