# Generated by Django 5.0.6 on 2024-09-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CsideApp', '0007_alter_cart_quantity'),
        ('SsideApp', '0004_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CsideApp.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SsideApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CsideApp.userregistration')),
            ],
        ),
    ]
