# Generated by Django 5.0.6 on 2024-09-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CsideApp', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
